/*
 Navicat Premium Data Transfer

 Source Server         : portal.pupuk-kujang.co.id
 Source Server Type    : MySQL
 Source Server Version : 100121
 Source Host           : portal.pupuk-kujang.co.id:3306
 Source Schema         : dev_db_pkl

 Target Server Type    : MySQL
 Target Server Version : 100121
 File Encoding         : 65001

 Date: 10/08/2021 08:42:33
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for notif
-- ----------------------------
DROP TABLE IF EXISTS `notif`;
CREATE TABLE `notif` (
  `id_notif` int(11) NOT NULL AUTO_INCREMENT,
  `link` varchar(255) DEFAULT NULL,
  `from` varchar(50) DEFAULT NULL,
  `from_name` varchar(100) DEFAULT NULL,
  `to` varchar(50) DEFAULT NULL,
  `desc` varchar(300) DEFAULT NULL,
  `status` enum('1','0') DEFAULT NULL,
  `date` date DEFAULT NULL,
  `time` time DEFAULT NULL,
  `icon` varchar(40) DEFAULT NULL,
  `type` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id_notif`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=360 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Records of notif
-- ----------------------------
BEGIN;
INSERT INTO `notif` VALUES (2, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/1', '1', 'Departemen PPSDM ', '92', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <i>Approval</i> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 17 Juli 2020', '1', '2020-07-13', '03:53:45', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (3, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/1', '1', 'Departemen PPSDM ', '2', 'Status Pendaftaran PKL kamu diubah menjadi <b>Mengundurkan Diri</b> oleh Administrator. Klik disini untuk memeriksa detail', '0', '2020-07-13', '04:20:34', 'fas fa-times-circle', 'warning');
INSERT INTO `notif` VALUES (4, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/1', '1', 'Departemen PPSDM ', '92', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <i>Approval</i> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 18 Juli 2020', '1', '2020-07-14', '09:05:29', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (11, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/1', '1', 'Departemen PPSDM ', NULL, 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 18 Juli 2020', '0', '2020-07-14', '10:01:35', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (14, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/1', '1', 'Departemen PPSDM ', '2', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja . Klik disini untuk memeriksa detail', '1', '2020-07-14', '10:34:37', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (15, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/detail/1', '1', 'Departemen PPSDM ', NULL, 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-07-14', '10:34:37', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (16, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/1', '1', 'Departemen PPSDM ', '2', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Departemen Pengantongan & Prod. Klik disini untuk memeriksa detail', '1', '2020-07-14', '10:42:23', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (17, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/detail/1', '1', 'Departemen PPSDM ', '92', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '1', '2020-07-14', '10:42:23', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (19, 'http://192.168.56.125/pelatihan/unit/permohonan_siswa/edit/2', '1', 'Departemen PPSDM ', '197', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 18 Juli 2020', '1', '2020-07-14', '03:21:04', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (22, 'http://192.168.56.125/pelatihan/siswa/riwayat/detail/2', '1', 'Departemen PPSDM ', '371', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '0', '2020-07-14', '03:29:46', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (23, 'http://192.168.56.125/pelatihan/unit/permohonan_siswa/detail/2', '1', 'Departemen PPSDM ', '197', 'Peserta PKL Siswa Bernama Siti Nurhayati Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '1', '2020-07-14', '03:29:46', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (27, 'http://192.168.56.140/pelatihan/mahasiswa/riwayat/detail/3', '1', 'Departemen PPSDM ', '2', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Kuota Penuh</b>. Klik disini untuk memeriksa detail', '0', '2020-07-15', '01:53:15', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (29, 'http://192.168.56.140/pelatihan/unit/permohonan_mahasiswa/edit/4', '1', 'Departemen PPSDM ', '92', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 19 Juli 2020', '1', '2020-07-15', '01:55:24', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (31, 'http://192.168.56.140/pelatihan/mahasiswa/riwayat/detail/4', '1', 'Departemen PPSDM ', '2', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Tidak Lolos Verifikasi Unit Kerja</b>. Klik disini untuk memeriksa detail', '0', '2020-07-15', '01:58:48', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (32, 'http://192.168.56.140/pelatihan/mahasiswa/riwayat/detail/4', '1', 'Departemen PPSDM ', '2', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Tidak Lolos Verifikasi Unit Kerja</b>. Klik disini untuk memeriksa detail', '0', '2020-07-15', '02:00:45', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (33, 'http://192.168.56.140/pelatihan/mahasiswa/riwayat/detail/4', '1', 'Departemen PPSDM ', '2', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Tidak Lolos Verifikasi Unit Kerja</b>. Klik disini untuk memeriksa detail', '0', '2020-07-15', '02:05:10', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (35, 'http://192.168.56.140/pelatihan/unit/permohonan_mahasiswa/edit/5', '1', 'Departemen PPSDM ', '92', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 19 Juli 2020', '1', '2020-07-15', '02:10:21', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (37, 'http://192.168.56.140/pelatihan/mahasiswa/riwayat/detail/5', '1', 'Departemen PPSDM ', '2', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Departemen Pengantongan & Prod. Klik disini untuk memeriksa detail', '0', '2020-07-15', '02:18:28', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (38, 'http://192.168.56.140/pelatihan/unit/permohonan_mahasiswa/detail/5', '1', 'Departemen PPSDM ', '92', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '1', '2020-07-15', '02:18:28', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (40, 'http://localhost/pelatihan/siswa/riwayat/detail/2', '1', 'Departemen PPSDM ', '371', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Tidak Lolos Verifikasi Unit Kerja</b>. Klik disini untuk memeriksa detail', '0', '2020-07-15', '09:14:05', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (42, 'http://192.168.137.1/pelatihan/siswa/riwayat/detail/6', '1', 'Administrator PPSDM', '371', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Kuota Penuh</b>. Klik disini untuk memeriksa detail', '0', '2020-07-15', '09:22:11', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (44, 'http://192.168.137.1/pelatihan/unit/permohonan_siswa/edit/7', '1', 'Administrator PPSDM', '197', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 19 Juli 2020', '1', '2020-07-15', '09:25:00', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (46, 'http://192.168.137.1/pelatihan/siswa/riwayat/detail/7', '1', 'Administrator PPSDM', '371', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '0', '2020-07-15', '09:27:24', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (47, 'http://192.168.137.1/pelatihan/unit/permohonan_siswa/detail/7', '1', 'Administrator PPSDM', '197', 'Peserta PKL Siswa Bernama Siti Nurhayati Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '1', '2020-07-15', '09:27:24', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (48, 'http://192.168.137.1/pelatihan/siswa/riwayat/detail/7', '1', 'Administrator PPSDM', '371', 'Status Pendaftaran PKL kamu diubah menjadi <b>Mengundurkan Diri</b> oleh Administrator. Klik disini untuk memeriksa detail', '0', '2020-07-15', '09:34:58', 'fas fa-times-circle', 'warning');
INSERT INTO `notif` VALUES (50, 'http://192.168.137.1/pelatihan/unit/permohonan_siswa/edit/8', '1', 'Administrator PPSDM', '197', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 19 Juli 2020', '1', '2020-07-15', '09:38:36', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (52, 'http://192.168.137.1/pelatihan/siswa/riwayat/detail/8', '1', 'Administrator PPSDM', '371', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '1', '2020-07-15', '09:39:16', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (53, 'http://192.168.137.1/pelatihan/unit/permohonan_siswa/detail/8', '1', 'Administrator PPSDM', '197', 'Peserta PKL Siswa Bernama Siti Nurhayati Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-07-15', '09:39:16', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (56, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/4', '1', 'Administrator PPSDM', '92', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Juli 2020', '0', '2020-07-16', '02:36:04', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (57, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/4', '1', 'Administrator PPSDM', '2', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Departemen Pengantongan & Prod. Klik disini untuk memeriksa detail', '0', '2020-07-16', '02:36:18', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (58, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/detail/4', '1', 'Administrator PPSDM', '92', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-07-16', '02:36:18', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (59, 'http://localhost/pelatihan/unit/permohonan_siswa/edit/7', '1', 'Administrator PPSDM', '197', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Juli 2020', '0', '2020-07-16', '03:32:52', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (60, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/3', '1', 'Administrator PPSDM', '92', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 21 Juli 2020', '1', '2020-07-17', '08:01:21', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (63, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/3', '1', 'Administrator PPSDM', '2', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Departemen Pengantongan & Prod. Klik disini untuk memeriksa detail', '0', '2020-07-17', '08:06:43', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (64, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/detail/3', '1', 'Administrator PPSDM', '92', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-07-17', '08:06:43', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (65, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/5', '1', 'Administrator PPSDM', '92', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 21 Juli 2020', '0', '2020-07-17', '08:09:44', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (66, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/5', '1', 'Administrator PPSDM', '2', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Departemen Pengantongan & Prod. Klik disini untuk memeriksa detail', '0', '2020-07-17', '08:18:00', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (67, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/detail/5', '1', 'Administrator PPSDM', '92', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-07-17', '08:18:00', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (68, 'http://localhost/pelatihan/unit/permohonan_siswa/edit/8', '1', 'Administrator PPSDM', '197', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 21 Juli 2020', '0', '2020-07-17', '08:19:57', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (69, 'http://localhost/pelatihan/siswa/riwayat/detail/8', '1', 'Administrator PPSDM', '371', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '0', '2020-07-17', '08:20:36', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (70, 'http://localhost/pelatihan/unit/permohonan_siswa/detail/8', '1', 'Administrator PPSDM', '197', 'Peserta PKL Siswa Bernama Siti Nurhayati Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '1', '2020-07-17', '08:20:36', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (72, 'http://localhost/pelatihan/siswa/riwayat/detail/8', '1', 'Administrator PPSDM', '371', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '0', '2020-07-17', '08:26:35', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (73, 'http://localhost/pelatihan/unit/permohonan_siswa/detail/8', '1', 'Administrator PPSDM', '197', 'Peserta PKL Siswa Bernama Siti Nurhayati Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '1', '2020-07-17', '08:26:35', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (74, 'http://localhost/pelatihan/mahasiswa/profil', '1', 'Diklat PKC', '372', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-07-17', '09:23:57', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (76, 'http://localhost/pelatihan/mahasiswa/profil/', '1', 'Administrator PPSDM', '372', 'Selamat akun kamu telah LOLOS VERIFIKASI', '0', '2020-07-17', '09:28:51', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (78, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/1', '1', 'Administrator PPSDM', '372', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Kuota Penuh</b>. Klik disini untuk memeriksa detail', '0', '2020-07-17', '09:32:07', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (80, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/2', '1', 'Administrator PPSDM', '92', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 24 Juli 2020', '0', '2020-07-20', '07:58:52', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (81, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/2', '1', 'Administrator PPSDM', '92', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 24 Juli 2020', '1', '2020-07-20', '08:04:20', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (83, 'http://192.168.56.203/pelatihan/mahasiswa/riwayat/detail/2', '1', 'Administrator PPSDM', '372', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Departemen Pengantongan & Prod. Klik disini untuk memeriksa detail', '0', '2020-07-20', '08:11:01', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (84, 'http://192.168.56.203/pelatihan/unit/permohonan_mahasiswa/detail/2', '1', 'Administrator PPSDM', '92', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-07-20', '08:11:01', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (86, 'http://192.168.56.203/pelatihan/siswa/profil', '1', 'Diklat PKC', '373', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-07-20', '08:41:03', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (87, 'http://192.168.56.203/pelatihan/siswa/profil', '1', 'Diklat PKC', '374', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-07-20', '08:41:50', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (90, 'http://192.168.56.203/pelatihan/siswa/profil/', '1', 'Administrator PPSDM', '374', 'Selamat akun kamu telah LOLOS VERIFIKASI', '0', '2020-07-20', '08:47:21', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (92, 'http://192.168.56.203/pelatihan/unit/permohonan_siswa/edit/3', '1', 'Administrator PPSDM', '197', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 24 Juli 2020', '1', '2020-07-20', '08:50:15', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (94, 'http://192.168.56.203/pelatihan/siswa/riwayat/detail/3', '1', 'Administrator PPSDM', '374', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '0', '2020-07-20', '08:52:41', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (95, 'http://192.168.56.203/pelatihan/unit/permohonan_siswa/detail/3', '1', 'Administrator PPSDM', '197', 'Peserta PKL Siswa Bernama Fahmi Asep Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-07-20', '08:52:41', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (97, 'http://192.168.56.203/pelatihan/unit/permohonan_siswa/edit/4', '1', 'Administrator PPSDM', '197', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 24 Juli 2020', '1', '2020-07-20', '09:36:42', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (99, 'http://192.168.56.203/pelatihan/siswa/riwayat/detail/4', '1', 'Administrator PPSDM', '374', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Tidak Lolos Verifikasi Unit Kerja</b>. Klik disini untuk memeriksa detail', '0', '2020-07-20', '09:41:58', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (101, 'http://192.168.56.203/pelatihan/siswa/riwayat/detail/4', '1', 'Administrator PPSDM', '374', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '0', '2020-07-20', '09:56:01', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (102, 'http://192.168.56.203/pelatihan/unit/permohonan_siswa/detail/4', '1', 'Administrator PPSDM', '197', 'Peserta PKL Siswa Bernama Fahmi Asep Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-07-20', '09:56:01', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (105, 'http://localhost/pelatihan/siswa/riwayat/detail/5', '1', 'Administrator PPSDM', '374', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Kuota Penuh</b>. Klik disini untuk memeriksa detail', '0', '2020-07-20', '02:56:07', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (106, 'http://localhost/pelatihan/mahasiswa/profil', '1', 'Diklat PKC', '375', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-08-03', '08:27:14', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (108, 'http://localhost/pelatihan/mahasiswa/profil/', '1', 'Administrator PPSDM', '375', 'Selamat akun kamu telah LOLOS VERIFIKASI', '0', '2020-08-03', '08:44:17', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (110, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/1', '1', 'Administrator PPSDM', '197', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 07 Agustus 2020', '0', '2020-08-03', '09:03:39', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (111, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/1', '1', 'Administrator PPSDM', '375', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '0', '2020-08-03', '09:04:21', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (112, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/detail/1', '1', 'Administrator PPSDM', '197', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-08-03', '09:04:21', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (114, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/2', '1', 'Administrator PPSDM', '197', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 07 Agustus 2020', '0', '2020-08-03', '09:10:17', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (115, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/2', '1', 'Administrator PPSDM', '375', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '0', '2020-08-03', '09:10:38', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (116, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/detail/2', '1', 'Administrator PPSDM', '197', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-08-03', '09:10:38', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (118, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/edit/3', '1', 'Administrator PPSDM', '197', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 07 Agustus 2020', '0', '2020-08-03', '09:15:58', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (119, 'http://localhost/pelatihan/mahasiswa/riwayat/detail/3', '1', 'Administrator PPSDM', '375', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '1', '2020-08-03', '09:16:12', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (120, 'http://localhost/pelatihan/unit/permohonan_mahasiswa/detail/3', '1', 'Administrator PPSDM', '197', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-08-03', '09:16:12', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (121, 'http://localhost/pelatihan/siswa/profil', '1', 'Diklat PKC', '376', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-08-03', '10:39:23', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (123, 'http://localhost/pelatihan/siswa/profil/', '1', 'Administrator PPSDM', '376', 'Selamat akun kamu telah LOLOS VERIFIKASI', '0', '2020-08-03', '10:45:17', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (125, 'http://localhost/pelatihan/unit/permohonan_siswa/edit/4', '1', 'Administrator PPSDM', '197', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 07 Agustus 2020', '0', '2020-08-03', '10:48:26', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (126, 'http://localhost/pelatihan/siswa/riwayat/detail/4', '1', 'Administrator PPSDM', '376', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '0', '2020-08-03', '10:48:49', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (127, 'http://localhost/pelatihan/unit/permohonan_siswa/detail/4', '1', 'Administrator PPSDM', '197', 'Peserta PKL Siswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-08-03', '10:48:49', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (128, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/profil', '1', 'Diklat PKC', '377', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-10-13', '10:19:08', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (130, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '377', 'Selamat akun kamu telah LOLOS VERIFIKASI', '0', '2020-10-13', '10:41:37', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (131, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '377', 'Selamat akun kamu telah LOLOS VERIFIKASI', '1', '2020-10-13', '10:42:56', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (133, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/5', '1', 'Administrator PPSDM', '377', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Kuota Penuh</b>. Klik disini untuk memeriksa detail', '1', '2020-10-13', '02:15:39', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (135, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_mahasiswa/edit/6', '1', 'Administrator PPSDM', '28', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 17 Oktober 2020', '1', '2020-10-13', '14:39:38', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (137, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/6', '1', 'Administrator PPSDM', '377', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Tidak Lolos Verifikasi Unit Kerja</b>. Klik disini untuk memeriksa detail', '0', '2020-11-16', '09:24:36', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (139, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/3', '1', 'Administrator PPSDM', '375', 'Status Pendaftaran PKL kamu diubah menjadi <b>Mengundurkan Diri</b> oleh Administrator. Klik disini untuk memeriksa detail', '0', '2020-11-18', '08:00:08', 'fas fa-times-circle', 'warning');
INSERT INTO `notif` VALUES (140, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/7', '1', 'Administrator PPSDM', '377', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Kuota Penuh</b>. Klik disini untuk memeriksa detail', '0', '2020-11-18', '08:03:43', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (142, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_mahasiswa/edit/8', '1', 'Administrator PPSDM', '179', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 22 November 2020', '0', '2020-11-18', '08:15:38', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (143, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/8', '1', 'Administrator PPSDM', '377', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf Departemen Pengembangan. Klik disini untuk memeriksa detail', '0', '2020-11-18', '08:22:56', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (144, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_mahasiswa/detail/8', '1', 'Administrator PPSDM', '179', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-11-18', '08:22:56', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (145, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/8', '1', 'Administrator PPSDM', '377', 'Status Pendaftaran PKL kamu diubah menjadi <b>Mengundurkan Diri</b> oleh Administrator. Klik disini untuk memeriksa detail', '0', '2020-11-18', '08:27:45', 'fas fa-times-circle', 'warning');
INSERT INTO `notif` VALUES (147, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/9', '1', 'Administrator PPSDM', '377', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Kuota Penuh</b>. Klik disini untuk memeriksa detail', '0', '2020-11-18', '08:48:25', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (155, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_siswa/edit/16', '1', 'Administrator PPSDM', '3', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 22 November 2020', '0', '2020-11-18', '09:19:42', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (157, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_mahasiswa/edit/17', '1', 'Administrator PPSDM', '3', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 22 November 2020', '0', '2020-11-18', '09:22:02', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (159, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/17', '1', 'Administrator PPSDM', '377', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Tidak Lolos Verifikasi Unit Kerja</b>. Klik disini untuk memeriksa detail', '0', '2020-11-18', '09:24:14', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (161, 'http://portal.pupuk-kujang.co.id/apps/pkl/siswa/riwayat/detail/16', '1', 'Administrator PPSDM', '376', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Direktorat Utama. Klik disini untuk memeriksa detail', '0', '2020-11-18', '09:25:46', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (162, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_siswa/detail/16', '1', 'Administrator PPSDM', '3', 'Peserta PKL Siswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-11-18', '09:25:46', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (164, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_mahasiswa/edit/18', '1', 'Administrator PPSDM', '3', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 22 November 2020', '0', '2020-11-18', '09:30:30', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (166, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/profil', '1', 'Diklat PKC', '378', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-11-18', '10:27:24', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (167, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/profil', '1', 'Diklat PKC', '379', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-11-18', '10:29:17', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (169, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '379', 'Selamat akun kamu telah LOLOS VERIFIKASI', '0', '2020-11-18', '10:39:06', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (170, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '379', 'Maaf akun kamu TIDAK LOLOS VERIFIKASI. Klik disini untuk memeriksa catatan perbaikan', '0', '2020-11-18', '10:39:36', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (172, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '379', 'Selamat akun kamu telah LOLOS VERIFIKASI', '0', '2020-11-18', '10:41:36', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (173, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/18', '1', 'Administrator PPSDM', '377', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Direktorat Utama. Klik disini untuk memeriksa detail', '0', '2020-11-18', '10:51:10', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (174, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_mahasiswa/detail/18', '1', 'Administrator PPSDM', '3', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-11-18', '10:51:10', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (175, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/18', '1', 'Administrator PPSDM', '377', 'Status Pendaftaran PKL kamu diubah menjadi <b>Mengundurkan Diri</b> oleh Administrator. Klik disini untuk memeriksa detail', '0', '2020-11-18', '10:51:21', 'fas fa-times-circle', 'warning');
INSERT INTO `notif` VALUES (177, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_mahasiswa/edit/20', '1', 'Administrator PPSDM', '197', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 22 November 2020', '0', '2020-11-18', '10:59:53', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (179, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/20', '1', 'Administrator PPSDM', '377', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Tidak Lolos Verifikasi Unit Kerja</b>. Klik disini untuk memeriksa detail', '0', '2020-11-18', '11:21:19', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (181, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_mahasiswa/edit/21', '1', 'Administrator PPSDM', '197', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 22 November 2020', '0', '2020-11-18', '11:25:23', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (182, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/riwayat/detail/21', '1', 'Administrator PPSDM', '377', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Klik disini untuk memeriksa detail', '1', '2020-11-18', '11:26:08', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (183, 'http://portal.pupuk-kujang.co.id/apps/pkl/unit/permohonan_mahasiswa/detail/21', '1', 'Administrator PPSDM', '197', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-11-18', '11:26:08', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (185, 'http://localhost/pkl/mahasiswa/profil', '1', 'Diklat PKC', '380', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '1', '2020-11-25', '07:33:44', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (187, 'http://localhost/pkl/mahasiswa/profil', '1', 'Diklat PKC', '381', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-11-25', '09:17:28', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (188, 'http://localhost/pkl/siswa/profil', '1', 'Diklat PKC', '382', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-11-25', '09:18:53', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (193, 'http://localhost/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '380', 'Selamat akun kamu telah LOLOS VERIFIKASI', '1', '2020-11-25', '09:47:37', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (194, 'http://localhost/pkl/siswa/profil/', '1', 'Administrator PPSDM', '382', 'Maaf akun kamu TIDAK LOLOS VERIFIKASI. Klik disini untuk memeriksa catatan perbaikan', '0', '2020-11-25', '09:47:47', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (196, 'http://localhost/pkl/siswa/profil/', '1', 'Administrator PPSDM', '382', 'Selamat akun kamu telah LOLOS VERIFIKASI', '1', '2020-11-25', '09:50:50', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (197, 'http://localhost/pkl/mahasiswa/profil', '1', 'Diklat PKC', '383', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '1', '2020-12-16', '09:13:27', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (202, 'http://localhost/pkl/siswa/profil', '1', 'Diklat PKC', '384', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2020-12-16', '09:52:55', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (211, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/27', '1', 'Administrator PPSDM', '3', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '20:29:43', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (213, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/28', '1', 'Administrator PPSDM', '6', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '20:34:24', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (215, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/29', '1', 'Administrator PPSDM', '5', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '20:35:40', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (217, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/30', '1', 'Administrator PPSDM', '7', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '20:52:29', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (219, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/31', '1', 'Administrator PPSDM', '4', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '20:55:57', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (221, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/32', '1', 'Administrator PPSDM', '5', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '20:58:50', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (223, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/33', '1', 'Administrator PPSDM', '6', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '21:01:16', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (224, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/34', '1', 'Administrator PPSDM', '7', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '21:02:15', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (225, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/35', '1', 'Administrator PPSDM', '4', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '21:03:53', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (226, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/36', '1', 'Administrator PPSDM', '5', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '21:06:13', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (227, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/37', '1', 'Administrator PPSDM', '6', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '21:09:52', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (228, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/39', '1', 'Administrator PPSDM', '5', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '21:11:56', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (229, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/40', '1', 'Administrator PPSDM', '7', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '21:12:15', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (231, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/41', '1', 'Administrator PPSDM', '3', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '21:15:02', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (233, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/42', '1', 'Administrator PPSDM', '7', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 20 Desember 2020', '0', '2020-12-16', '21:17:37', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (240, 'http://localhost/pkl/unit/permohonan_siswa/edit/3', '1', 'Administrator PPSDM', '6', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 21 Desember 2020', '0', '2020-12-17', '09:16:07', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (242, 'http://localhost/pkl/mahasiswa/riwayat/detail/4', '1', 'Administrator PPSDM', '380', 'Maaf pendaftaran PKL kamu <b>DITOLAK</b> karena <b>Kuota Penuh</b>. Klik disini untuk memeriksa detail', '1', '2020-12-17', '10:55:53', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (244, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/5', '1', 'Administrator PPSDM', '197', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 21 Desember 2020', '0', '2020-12-17', '15:21:08', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (247, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/5', '1', 'Administrator PPSDM', '7', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 21 Desember 2020', '0', '2020-12-17', '18:17:37', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (249, 'http://localhost/pkl/mahasiswa/riwayat/detail/5', '1', 'Administrator PPSDM', '380', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja . Klik disini untuk memeriksa detail', '0', '2020-12-17', '19:22:06', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (250, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/5', '1', 'Administrator PPSDM', NULL, 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-12-17', '19:22:06', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (251, 'http://localhost/pkl/mahasiswa/riwayat/detail/5', '1', 'Administrator PPSDM', '380', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja . Klik disini untuk memeriksa detail', '0', '2020-12-17', '19:22:45', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (252, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/5', '1', 'Administrator PPSDM', NULL, 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-12-17', '19:22:45', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (253, 'http://localhost/pkl/mahasiswa/riwayat/detail/5', '1', 'Administrator PPSDM', '380', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja . Klik disini untuk memeriksa detail', '0', '2020-12-17', '19:28:27', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (254, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/5', '1', 'Administrator PPSDM', NULL, 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-12-17', '19:28:27', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (255, 'http://localhost/pkl/mahasiswa/riwayat/detail/5', '1', 'Administrator PPSDM', '380', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Departemen Hukum&Administrasi Per. Klik disini untuk memeriksa detail', '0', '2020-12-17', '19:29:47', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (256, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/5', '1', 'Administrator PPSDM', NULL, 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-12-17', '19:29:47', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (257, 'http://localhost/pkl/mahasiswa/riwayat/detail/5', '1', 'Administrator PPSDM', '380', 'Selamat kamu telah <b>TERDAFTAR</b> sebagai peserta PKL pada unit kerja Departemen Hukum&Administrasi Per. Klik disini untuk memeriksa detail', '1', '2020-12-17', '19:31:39', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (258, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/5', '1', 'Administrator PPSDM', '7', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2020-12-17', '19:31:39', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (259, 'http://localhost/pkl/mahasiswa/profil', '1', 'Diklat PKC', '385', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '1', '2021-01-04', '10:09:32', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (261, 'http://localhost/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '385', 'Selamat akun kamu telah LOLOS VERIFIKASI', '1', '2021-01-04', '10:18:42', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (262, 'http://localhost/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '385', 'Akun kamu Tidak Lolos Verifikasi. Klik disini untuk memeriksa catatan perbaikan', '1', '2021-01-04', '10:43:14', 'far fa-comment-dots', 'danger');
INSERT INTO `notif` VALUES (263, 'http://localhost/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '385', 'Selamat akun kamu telah Lolos Verifikasi. Sekarang kamu bisa melakukan pendaftaran PKL', '0', '2021-01-04', '10:47:46', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (265, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/1', '1', 'Administrator PPSDM', '197', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 08 Januari 2021', '0', '2021-01-04', '13:36:18', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (267, 'http://localhost/pkl/mahasiswa/riwayat/detail/1', '1', 'Administrator PPSDM', '385', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '1', '2021-01-04', '13:48:00', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (268, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/1', '1', 'Administrator PPSDM', '197', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-04', '13:48:00', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (269, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/1', '1', 'Administrator PPSDM', '197', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 08 Januari 2021', '0', '2021-01-04', '14:55:27', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (271, 'http://localhost/pkl/mahasiswa/riwayat/detail/1', '1', 'Administrator PPSDM', '385', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '1', '2021-01-04', '14:56:04', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (272, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/1', '1', 'Administrator PPSDM', '197', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-04', '14:56:04', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (273, 'http://localhost/pkl/mahasiswa/riwayat/detail/1', '1', 'Administrator PPSDM', '385', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '1', '2021-01-04', '14:58:36', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (274, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/1', '1', 'Administrator PPSDM', '197', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit Resmi <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-04', '14:58:36', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (295, 'http://localhost/pkl/unit/permohonan_siswa/edit/1', '1', 'Administrator PPSDM', '9', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 09 Januari 2021', '0', '2021-01-05', '14:43:55', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (298, 'http://localhost/pkl/unit/permohonan_siswa/detail/1', '1', 'Administrator PPSDM', '9', 'Peserta PKL Siswa Bernama Asep Saepul Pahmit Aja  <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-05', '14:44:54', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (301, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/2', '1', 'Administrator PPSDM', '14', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 09 Januari 2021', '0', '2021-01-05', '15:19:45', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (303, 'http://localhost/pkl/mahasiswa/riwayat/detail/2', '1', 'Administrator PPSDM', '385', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Direktorat Produksi. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '0', '2021-01-05', '15:20:49', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (304, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/2', '1', 'Administrator PPSDM', '14', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit  <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-05', '15:20:49', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (305, 'http://localhost/pkl/mahasiswa/riwayat/detail/2', '1', 'Administrator PPSDM', '385', 'Status Pendaftaran PKL kamu diubah menjadi <b>Mengundurkan Diri</b> oleh Administrator. Klik disini untuk memeriksa detail', '1', '2021-01-05', '15:22:38', 'fas fa-times-circle', 'warning');
INSERT INTO `notif` VALUES (307, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/3', '1', 'Administrator PPSDM', '11', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 09 Januari 2021', '0', '2021-01-05', '15:28:29', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (309, 'http://localhost/pkl/mahasiswa/riwayat/detail/3', '1', 'Administrator PPSDM', '385', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Satuan Pengawasan Intern. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '1', '2021-01-05', '15:29:31', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (310, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/3', '1', 'Administrator PPSDM', '11', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit  <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-05', '15:29:31', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (312, 'http://localhost/pkl/unit/permohonan_mahasiswa/edit/1', '1', 'Administrator PPSDM', '197', 'Ada satu Mahasiswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 11 Januari 2021', '0', '2021-01-07', '09:05:36', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (314, 'http://localhost/pkl/mahasiswa/riwayat/detail/1', '1', 'Administrator PPSDM', '385', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '0', '2021-01-07', '09:11:21', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (315, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/1', '1', 'Administrator PPSDM', '197', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit  <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-07', '09:11:21', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (317, 'http://localhost/pkl/mahasiswa/riwayat/detail/1', '1', 'Administrator PPSDM', '385', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Staf GM.Tek&Bang& SI Penugasan TI PI PKC. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '1', '2021-01-07', '09:18:09', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (318, 'http://localhost/pkl/unit/permohonan_mahasiswa/detail/1', '1', 'Administrator PPSDM', '197', 'Peserta PKL Mahasiswa Bernama Asep Saepul Pahmit  <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-07', '09:18:09', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (322, 'http://localhost/pkl/unit/permohonan_siswa/edit/7', '1', 'Administrator PPSDM', '9', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 11 Januari 2021', '0', '2021-01-07', '09:30:18', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (324, 'http://localhost/pkl/siswa/riwayat/detail/7', '1', 'Administrator PPSDM', '386', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Departemen Tata Kelola&Manajemen. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '1', '2021-01-07', '09:31:48', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (325, 'http://localhost/pkl/unit/permohonan_siswa/detail/7', '1', 'Administrator PPSDM', '9', 'Peserta PKL Siswa Bernama Asep Saepul Pahmit Aja  <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-07', '09:31:48', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (326, 'http://localhost/pkl/siswa/profil', '1', 'Diklat PKC', '387', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2021-01-07', '12:55:10', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (328, 'http://localhost/pkl/siswa/profil/', '1', 'Administrator PPSDM', '387', 'Selamat akun kamu telah Lolos Verifikasi', '1', '2021-01-07', '12:57:36', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (330, 'http://localhost/pkl/unit/permohonan_siswa/edit/8', '1', 'Administrator PPSDM', '7', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 11 Januari 2021', '0', '2021-01-07', '12:59:16', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (332, 'http://localhost/pkl/siswa/riwayat/detail/8', '1', 'Administrator PPSDM', '387', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Departemen Hukum&Administrasi Per. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '1', '2021-01-07', '13:00:26', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (333, 'http://localhost/pkl/unit/permohonan_siswa/detail/8', '1', 'Administrator PPSDM', '7', 'Peserta PKL Siswa Bernama test siswa  <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-07', '13:00:26', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (334, 'http://localhost/pkl/siswa/riwayat/detail/8', '1', 'Administrator PPSDM', '387', 'Status Pendaftaran PKL kamu diubah menjadi <b>Mengundurkan Diri</b> oleh Administrator. Klik disini untuk memeriksa detail', '0', '2021-01-07', '13:02:22', 'fas fa-times-circle', 'warning');
INSERT INTO `notif` VALUES (335, 'http://localhost/pkl/unit/penilaian/index/8', '387', 'test siswa', '7', 'Peserta PKL <b>test siswa</b>  mengupload laporan PKL. Mohon diperiksa untuk menambahkan penilaian peserta PKL', '0', '2021-01-07', '13:06:36', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (337, 'http://localhost/pkl/unit/penilaian/index/8', '387', 'test siswa', '7', 'Peserta PKL <b>test siswa</b>  mengupload laporan PKL. Mohon diperiksa untuk menambahkan penilaian peserta PKL', '1', '2021-01-07', '13:06:47', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (339, 'http://localhost/pkl/mahasiswa/profil/', '1', 'Administrator PPSDM', '385', 'Selamat akun kamu telah Lolos Verifikasi. Sekarang kamu bisa melakukan pendaftaran PKL', '1', '2021-01-07', '13:12:18', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (340, 'http://localhost/pkl/unit/penilaian/index/1', '385', 'Asep Saepul Pahmit', '197', 'Peserta PKL <b>Asep Saepul Pahmit</b>  mengupload laporan PKL. Mohon diperiksa untuk menambahkan penilaian peserta PKL', '0', '2021-01-08', '07:43:24', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (346, 'http://localhost/pkl/admin/permohonan_mahasiswa/edit/1', 'direct', 'direct', '1', 'Nilai PKL Mahasiswa <b>Asep Saepul Pahmit</b> Telah Diinputkan Oleh Unit Kerja melalui Direct Link. Klik untuk melihat detail & mencetak lembar penilaian', '1', '2021-01-08', '08:37:00', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (347, 'http://localhost/pkl/admin/permohonan_siswa/edit/8', 'direct', 'direct', '1', 'Nilai PKL Mahasiswa <b>test siswa</b> Telah Diinputkan Oleh Unit Kerja melalui Direct Link. Klik untuk melihat detail & mencetak lembar penilaian', '1', '2021-01-08', '08:42:13', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (348, 'http://localhost/pkl/unit/penilaian/index/7', '386', 'Asep Saepul Pahmit Aja', '9', 'Peserta PKL <b>Asep Saepul Pahmit Aja</b>  mengupload laporan PKL. Mohon diperiksa untuk menambahkan penilaian peserta PKL', '1', '2021-01-08', '09:06:00', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (349, 'http://localhost/pkl/admin/permohonan_siswa/edit/7', '386', 'Asep Saepul Pahmit Aja', '1', 'Peserta PKL <b>Asep Saepul Pahmit Aja</b>  mengupload laporan PKL.', '1', '2021-01-08', '09:06:00', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (350, 'http://localhost/pkl/admin/permohonan_siswa/edit/7', '9', 'Departemen Tata Kelola&Manajemen', '1', 'Nilai PKL Mahasiswa <b>Asep Saepul Pahmit Aja</b> dengan <b>ID 7</b> Telah Diinputkan Oleh Unit Kerja <b>Departemen Tata Kelola&Manajemen</b>. Klik untuk melihat detail & mencetak lembar penilaian', '0', '2021-01-08', '09:08:24', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (351, 'http://localhost/pkl/mahasiswa/profil', '1', 'Diklat PKC', '388', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2021-01-18', '14:11:08', 'fas fa-info-circle', 'danger');
INSERT INTO `notif` VALUES (352, 'http://localhost/pkl/unit/permohonan_siswa/edit/8', '1', 'Administrator PPSDM', '6', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 22 Januari 2021', '0', '2021-01-18', '14:21:00', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (353, 'http://localhost/pkl/admin/permohonan_siswa/edit/8', '1', 'Administrator PPSDM', '1', 'Pendaftaran PKL Mahasiswa  <b>test siswa</b> Telah Disetujui Oleh Unit Kerja melalui Direct Link. Klik untuk melihat detail dan merubah status', '1', '2021-01-18', '14:21:53', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (354, 'http://localhost/pkl/admin/permohonan_siswa/edit/1', '387', 'test siswa', '1', 'Pendaftaran PKL Siswa test siswa dengan ID 1 Menunggu Untuk Diverifikasi', '1', '2021-01-18', '14:34:31', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (355, 'http://localhost/pkl/unit/permohonan_siswa/edit/1', '1', 'Administrator PPSDM', '7', 'Ada satu Siswa peserta PKL baru yang menunggu <b>Approval</b> dari Unit Kerja Anda. Mohon lakukan approval sebelum tanggal 22 Januari 2021', '0', '2021-01-18', '14:35:49', 'fas fa-info', 'info');
INSERT INTO `notif` VALUES (356, 'http://localhost/pkl/admin/permohonan_siswa/edit/1', '1', 'Administrator PPSDM', '1', 'Pendaftaran PKL Mahasiswa  <b>test siswa</b> Telah Disetujui Oleh Unit Kerja melalui Direct Link. Klik untuk melihat detail dan merubah status', '1', '2021-01-18', '14:36:44', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (357, 'http://localhost/pkl/siswa/riwayat/detail/1', '1', 'Administrator PPSDM', '387', 'Selamat kamu telah <b>Diterima</b> sebagai peserta PKL pada unit kerja Departemen Hukum&Administrasi Per. Mohon lakukan konfirmasi kesediaan atau pendaftaran ulang maksimal 1 minggu sebelum pelaksanaan PKL. Klik disini untuk memeriksa detail', '1', '2021-01-18', '14:37:54', 'fas fa-check', 'success');
INSERT INTO `notif` VALUES (358, 'http://localhost/pkl/unit/permohonan_siswa/detail/1', '1', 'Administrator PPSDM', '7', 'Peserta PKL Siswa Bernama test siswa  <b>Terdaftar</b> Pada Unit Kerja Anda. Klik disini untuk melihat detail', '0', '2021-01-18', '14:37:54', 'fas fa-info', 'success');
INSERT INTO `notif` VALUES (359, 'http://portal.pupuk-kujang.co.id/apps/pkl/mahasiswa/profil', '1', 'Diklat PKC', '389', 'Akun Kamu Belum Terverifikasi. Silahkan lakukan update profil terlebih dahulu', '0', '2021-06-30', '00:22:03', 'fas fa-info-circle', 'danger');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
